export const dummyClients = [
    {
        id: 1,
        name: 'Client A',
        subscriptionType: 'Premium',
        apiKey: 'abcd1234',
        contact: 'clientA@example.com',
        totalUsage: 500,
        revenue: '$100000',
        paymentStatus: 'Paid',
      },
      {
        id: 2,
        name: 'Client B',
        subscriptionType: 'Standard',
        apiKey: 'efgh5678',
        contact: 'clientB@example.com',
        totalUsage: 300,
        revenue: '$60056554',
        paymentStatus: 'Unpaid',
      },
      {
        id: 3,
        name: 'Client A',
        subscriptionType: 'Premium',
        apiKey: 'abcd1234',
        contact: 'clientA@example.com',
        totalUsage: 500,
        revenue: '$1000',
        paymentStatus: 'Paid',
      },
      {
        id: 4,
        name: 'Client B',
        subscriptionType: 'Standard',
        apiKey: 'efgh5678',
        contact: 'clientB@example.com',
        totalUsage: 300,
        revenue: '$600',
        paymentStatus: 'Unpaid',
      },
      {
        id: 5,
        name: 'Client A',
        subscriptionType: 'Premium',
        apiKey: 'abcd1234',
        contact: 'clientA@example.com',
        totalUsage: 500,
        revenue: '$1000',
        paymentStatus: 'Paid',
      },
      {
        id: 6,
        name: 'Client B',
        subscriptionType: 'Standard',
        apiKey: 'efgh5678',
        contact: 'clientB@example.com',
        totalUsage: 300,
        revenue: '$600',
        paymentStatus: 'Unpaid',
      },
      {
        id: 7,
        name: 'Client A',
        subscriptionType: 'Premium',
        apiKey: 'abcd1234',
        contact: 'clientA@example.com',
        totalUsage: 500,
        revenue: '$1000',
        paymentStatus: 'Paid',
      },
      {
        id: 8,
        name: 'Client B',
        subscriptionType: 'Standard',
        apiKey: 'efgh5678',
        contact: 'clientB@example.com',
        totalUsage: 300,
        revenue: '$600',
        paymentStatus: 'Unpaid',
      }
]